[project]
name = "dati-immobiliari"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.1.3",
    "streamlit>=1.40.2",
]
